CONFIG_BT=y
CONFIG_LOG=y
CONFIG_BT_SMP=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DIS=y
CONFIG_BT_DIS_PNP=n
CONFIG_BT_BAS=y
CONFIG_BT_HRS=y
CONFIG_BT_DEVICE_NAME="Zephyr Heartrate Sens"
CONFIG_BT_DEVICE_APPEARANCE=833

# Disable UART driver
#CONFIG_SERIAL=n

# Disable Console
#CONFIG_CONSOLE=n
#CONFIG_UART_CONSOLE=n
